// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    GlobalSetting: typeof import('./components/GlobalSetting/index.vue')['default']
    TipIcon: typeof import('./components/TipIcon/index.vue')['default']
  }
}

export { }
